#!/usr/bin/env node

var fs = require("fs");
var igor = require('./igor.js');
var argv = require('yargs')
    .demand(1)
    .argv;

var plugin = argv._[0];
var options = {}
for(var key in argv) {
	if(key != "_" && key != "$0") options[key] = argv[key];
}

var input = null;
if(argv._.length == 1) {
	// read input from standard input...
	var stdin = process.stdin,
	    inputChunks = [];
	 
	stdin.resume();
	stdin.setEncoding('utf8');
	 
	stdin.on('data', function (chunk) {
	    inputChunks.push(chunk);
	});
	 
	stdin.on('end', function () {
	    var dataRead = inputChunks.join();
	    onInputRead(dataRead);
	});
} else {
	var inputFile = argv._[1];
	fs.readFile(inputFile, "utf-8", function(err, data) {
		if(!err) {
			onInputRead(data)
		} else {
			console.error(err);
		}
	});
}

function onInputRead(input) {
	igor(plugin, input, options, function(err, result) {
		if(!err) {
			console.log(result);
		} else {
			console.error(err);
		}
	});
}
